---
title: "Homework 5"
author: "Michael Yan"
date: "May 27, 2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readr)
```

```{r questions, echo=TRUE}
#1. A delimiter is a character that acts as a separator between characters in a file. 
# The most popular one that statisticians use is the "comma"

#2. An R-package is something that comes installed in R.
# A package lets the user do many things, # such as reading in data.
# When we # don't have a package installed:
# the library() gives an error
# require() results in a warning message

#3. Differences between the default behavior for read_csv() and read.csv() is: 
# read_csv occurs in the tidyverse package read_csv() will conver them to tibbles, tbls, etc.
# whereas read.csv occurs in base R. 
# Read.csv reads character #variables as factors, which doesn't convert columns to datatypes.  
```

```{r Breastcancer, echo = TRUE, message=FALSE, warning=FALSE}
cancerData <- read_tsv("BreastCancer.dat")  # read in a tab delimited file. 
cancerData <- tbl_df(cancerData) # conver the file to a tibble. 
cancerData

cancerdatacol <- select(cancerData, size) # take only the size column 
cancerdatacol

cancerdatarows <- cancerData[1:3, ] # take only the first 3 rows
cancerdatarows

stats <- cancerData %>% group_by(meno) %>% summarise(avgs=mean(size), stdev=sd(size), obs=n())
stats

```

```{r mosquitoes, echo = TRUE, message=FALSE, warning=FALSE}

mosquitoData <- read_delim("mosquito.txt", delim = '&')
mosquitoData
mosquitoData2 <- read_tsv("mosquito2.txt", 
                          colnames <- c("Day", "Cage", "trt", "Response"))
mosquitoData2
mosquitoFullData <- rbind(mosquitoData, mosquitoData2) 
Hours <- mosquitoFullData %>% mutate(TotalHours=(Response * 60))
Hours 

Lspan <- Hours %>% {
  mutate(Hours, Span = ifelse(Response <= 40 & Response >=20, 'medium', ifelse(Response > 40, 'long', ifelse(Response < 20, 'short', NA))))
}

Lspan

# The rbind function takes arguments from a vector, matrix, or dataframe and combines them by
# columns or rows, respectively. 
```

```{r effort, echo=TRUE, message=FALSE, warning=FALSE}
library(haven)
effortData <- read_stata("effort.dta")
effortData

effort <- effortData %>% filter(effort > 10)
effort
```

```{r chicken, echo=TRUE, message=FALSE, warning=FALSE}
library(readxl)
sheepData <- read_excel("Chickens.xlsx", sheet="Sheep")
sheepData
```


